about/urls.py
from django.urls import path
from .views import about
app_name = 'about'
urlpatterns = [
    path('', about , name = 'about'),
]

blog/urls.py
from django.urls import path
from .views import blog,detiel, addblog, updateblog,deleteblog
app_name = 'blog'
urlpatterns = [
    path('', blog , name = 'blog'),
    path('detiel/<int:id>', detiel, name = 'detiel'),
    path('addblog/', addblog, name = 'addblog'),
    path('updateblog/<int:id>', updateblog, name = 'updateblog'),
     path('deleteblog/<int:id>', deleteblog, name = 'deleteblog'),
]

contact/urls.py
from django.urls import path
from .views import contact
app_name = 'contact'
urlpatterns = [
    path('', contact , name = 'contact'),
]

myapp/urls.py
from django.urls import path
from .views import home
urlpatterns = [
    path('', home, name = 'home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('services/', include('services.urls')),
    path('work/', include('work.urls')),
    path('contact/', include('contact.urls')),
    # path('blogapp/', include('blogapp.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from .views import services
app_name = 'services'
urlpatterns = [
    path('', services , name = 'services'),
]

work/urls.py
from django.urls import path
from .views import work, addwork
app_name = 'work'
urlpatterns = [
    path('', work, name = 'work'),
     path('addwork/', addwork, name = 'addwork'),
]

about/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    img = models.ImageField(upload_to = "about/")
    html = models.CharField(max_length=15)
    css = models.CharField(max_length=15)
    py = models.CharField(max_length=15)
    js = models.CharField(max_length=15)

    def __str__(self):
        return self.email

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    img = models.ImageField(upload_to = "blog/")
    imgAuthor = models.ImageField(upload_to = "blog/")
    author = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    blog_count = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title} {self.author}'

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    text = models.TextField()

    def __str_(self):
        return self.name

myapp/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models

# Create your models here.
class Services(models.Model):
    work = models.CharField(max_length=20)
    year = models.CharField(max_length=2)
    client = models.CharField(max_length=5)
    won = models.CharField(max_length=3)

    def __str__(self):
        return f'services'

work/models.py
from django.db import models

# Create your models here.
class Work(models.Model):
    img = models.ImageField(upload_to = "work/")
    name = models.CharField(max_length=40)
    title = models.CharField(max_length=30)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

about/forms.py
from django.forms import ModelForm
from .models import About

class AboutForm(ModelForm):
    class Meta:
        model = About
        fields = ['email', 'phone', 'img', 'html', 'css', 'py', 'js']

blog/forms.py
from django.forms import ModelForm
from .models import Blog

class AddBlog(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body', 'img', 'imgAuthor', 'author']
    
    # def __init__(self, *args, **kwargs):
    #     super(AddBlog,self).__init__(*args, **kwargs)
    #     self.

contact/forms.py
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'text']

work/forms.py
from django.forms import ModelForm
from .models import Work

class AddWork(ModelForm):
    class Meta:
        model = Work
        fields = ['img', 'name', 'title']
    

about/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import About
from .forms import AboutForm
# Create your views here.
def about(request):
    about = About.objects.all()
    return render(request, 'about.html', {'about': about})

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Blog
from .forms import AddBlog
# Create your views here.
def blog(request):
    yus = request.GET.get('yus')
    print(yus)
    obj = Blog.objects.all()
    if request.GET:
        obj = Blog.objects.filter(title__contains=yus)
    return render(request,'blog.html', {'obj': obj})

def detiel(request,id):
    blog = get_object_or_404(Blog,id=id)
    blog.blog_count += 1
    blog.save()
    return render(request, 'detiel.html', {'blog': blog,})

def addblog(request):
    form = AddBlog()
    if request.method == 'POST':
        form = AddBlog(request.POST, request.FILES)
        if form.is_valid():
            
            form.save()
            return redirect('blog:blog')
    return render(request, 'addblog.html', {'addblog': form})

def updateblog(request,id):
    blog = get_object_or_404(Blog, id=id)
    if request.method == 'POST':
        form = AddBlog(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('blog:blog')
    else:
        form = AddBlog(instance=blog)
    return render(request,'updateblog.html', {'form': form, 'blog':blog})

def deleteblog(request,id):
    blog = get_object_or_404(Blog, id=id)
    form = AddBlog(request.POST, instance=blog)
    if request.method == 'POST':
        blog.delete()
        return redirect('blog:blog')
    return render(request,'deleteblog.html', {'form': form, 'blog': blog})

contact/views.py
from django.shortcuts import render, redirect
from .models import Contact
from .forms import ContactForm
# Create your views here.
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form':form})

myapp/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

services/views.py
from django.shortcuts import render
from .models import Services
# Create your views here.

def services(request):
    services = Services.objects.all()
    return render(request, 'services.html', {'services': services})

work/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Work
from .forms import AddWork
# Create your views here.
def work(request):
    obj = Work.objects.all()
    return render(request, 'work.html', {'obj':obj})


def addwork(request):
    form = AddWork()
    if request.method == 'POST':
        form = AddWork(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('work:work')
    return render(request,'addwork.html',{'addwork': form})

blog/templates/addblog.html
<form action="{% url 'blog:addblog' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="group">
        <label for="" >Title</label>
        {{addblog.title}} <br><br>

        <label for="">Body</label>
        {{addblog.body}}<br><br>

        <label for="">Img</label>
        {{addblog.img}}<br><br>

        <label for="">ImgAuthor</label>
        {{addblog.imgAuthor}}<br><br>

        <label for="">Author</label>
        {{addblog.author}}<br><br>
        
    </div>
    <input type="submit" value="OK">
</form>

blog/templates/blog.html
{% extends 'index.html' %}
{% load static %}
{% block title %} BLOG {% endblock %}
{% block content %}
<br><br><br>
   
    <section id="blog" class="blog-mf sect-pt4 route">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="title-box text-center">
                        <h3 class="title-a">
                            Blog
                        </h3>
                        <p class="subtitle-a">
                            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                        </p>
                        <div class="line-mf"></div>
                    </div>
                </div>
            </div>
            <a href="{% url 'blog:addblog' %}" class="nav-link text-center h3">AddBlog</a>
           
            <div class="row">
                {% for i in obj %}
                    <div class="col-md-4">
                        <div class="card card-blog">
                            <div class="card-img">
                                <a href="{% url 'blog:detiel' i.id %}"><img src="{{i.img.url}}" alt="" class="img-fluid"></a>
                            </div>
                            <div class="card-body">
                                <div class="card-category-box">
                                    <div class="card-category">
                                        <h6 class="category">Web Design</h6>
                                    </div>
                                </div>
                                <h3 class="card-title"><a href="{% url 'blog:detiel' i.id %}">{{ i.title.upper }}</a></h3>
                                <p class="card-description">
                                    {{i.body| truncatechars:100| safe }}
                                </p>
                            </div>
                            <p><a href="{% url 'blog:updateblog' i.id %}" class="nav-link text-center h4">UpdateBlog</a></p>
                            <p><a href="{% url 'blog:deleteblog' i.id %}" class="nav-link text-center h4">DeleteBlog</a></p>
                            <div class="card-footer">
                                <div class="post-author">
                                    <a href="#">
                                        <img src="{{i.imgAuthor.url}}" alt="" class="avatar rounded-circle">
                                        <span class="author">{{i.author}}</span>
                                    </a>
                                </div><br>
                                <div class="post-date">
                                    <span class="ion-ios-clock-outline"></span> {{i.date|date:"d M Y"}}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
    </section>
{% endblock %}

blog/templates/deleteblog.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>{{blog.title}}</h1>
    <input type="submit" value="OK"> <br><br>
    <a href="{% url 'blog:blog' %}">ortga</a>
</form>

blog/templates/detiel.html
{% extends 'index.html' %}
{% block title %} {{blog.title}} {% endblock %}
{% block content %}
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<div class="container">
    <br><br><br><br>
    <div class="row pt-3">
        <div class="col-md-10">
            <marquee behavior="alternate" direction="left" bgcolor="#ffcc00"><span><i class="fas fa-eye fa-2x p-2" > <span >{{blog.blog_count}} views</span></i></span></marquee>
            <div class="card card-blog">
                <div class="card-img">
                   <img src="{{blog.img.url}}" alt="" class="img-fluid">
                </div>
                <div class="card-body">
                    <div class="card-category-box">
                        <div class="card-category">
                            <h6 class="category">Web Design</h6>
                        </div>
                    </div>
                    <h2 class="card-title text-center ">{{ blog.title.upper }}</h2>
                    <p class="card-description">
                        {{blog.body}}
                    </p>
                </div>
                <div class="card-footer">
                    <div class="post-author">
                        <a href="{% url 'blog:blog' %}">
                            <img src="{{blog.imgAuthor.url}}" alt="" class="avatar rounded-circle">
                            <span class="author">{{blog.author}}</span>
                        </a>
                    </div>
                    
                    <div class="post-date">
                        <span class="ion-ios-clock-outline"> {{blog.date}}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/updateblog.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="group">
        <label for="" >Title</label>
        {{form.title}} <br><br>

        <label for="">Body</label>
        {{form.body}}<br><br>

        <label for="">Img</label>
        {{form.img}}<br><br>

        <label for="">ImgAuthor</label>
        {{form.imgAuthor}}<br><br>

        <label for="">Author</label>
        {{form.author}}<br><br>
        
    </div>
    <input type="submit" value="OK">
</form>

myapp/templates/home.html
{% extends 'index.html' %}
{% load static %}
{% block title %} HOME {% endblock %}

{% block content %}
<div id="home" class="intro route bg-image mt-5" style="background-image: url({% static 'img/intro-bg.jpg' %})">
    <div class="overlay-itro"></div>
    <div class="intro-content display-table">
        <div class="table-cell">
            <div class="container">
                <!--<p class="display-6 color-d">Hello, world!</p>-->
                <h1 class="intro-title mb-4">I am Yusuf Allayorov</h1>
                <p class="intro-subtitle"><span class="text-slider-items">Web Developer,
                        Frontend Developer,Backend Developer</span><strong class="text-slider"></strong></p>
                <!-- <p class="pt-3"><a class="btn btn-primary btn js-scroll px-4" href="#about" role="button">Learn More</a></p> -->
            </div>
        </div>
    </div>
</div>


{% endblock %}

myapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!--/ Bootstrap fayli /-->
    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!--  CSS kutubxonalari -->
    <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

    <!--/ Asosiy CSS fayli /-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!--/ Menu boshlandi /-->
    <nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top bg-dark" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll font-weight-bold" href="{% url 'home' %}">Dev<span style="color:deeppink;">Yusuf</span></a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
                aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span></span>
                <span></span>
                <span></span>
            </button>
            <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link js-scroll " href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll" href="{% url 'about:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll" href="{% url 'services:services' %}">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll" href="{% url 'work:work' %}">Work</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll" href="{% url 'blog:blog' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll" href="{% url 'contact:contact'%}">Contact</a>
                    </li>
                    <nav class="navbar p-0">
                        <form class="form-inline">
                          <input class="form-control mr-sm-2" type="text" name="yus" placeholder="Search">
                          <button class="btn btn-success" type="submit">Search</button>
                        </form>
                    </nav>
                </ul>
            </div>
        </div>
    </nav>
    <!--/ Menu tugadi /-->
    {% block content %}
    <!--/ Slayd boshlandi /-->
    
    <!--/  Slayd tugadi /-->

    <!--/  About boshlandi /-->
    
    <!--/  About tugadi /-->

    <!--/ Servisce boshlandi /-->
    
    <!--/ Service tugadi /-->

    

    <!--/ Portfolio boshlandi /-->
    
    <!--/ Portfolio tugadi /-->

    <!--/ Section Testimonials Star /-->
    

    <!--/ Blog boshlandi /-->
    
   
    <!--/ Blog tugadi /-->

    <!--/ Contact-Footer boshlandi /-->
    
    <!--/  Contact-footer tugadi /-->
    
    
    {% endblock %}
    <footer class="bg-dark pt-5">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="copyright-box">
                        <p class="copyright">&copy; Copyright <strong>DevYusuf</strong>. All Rights Reserved</p>
                        <div class="credits">
                            Designed by <a href="{% url 'home' %}">Allayorov Yusuf</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
    <div id="preloader"></div>
    <!-- JavaScript kutubxonalari -->
    <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
    <script src="{% static 'lib/popper/popper.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/counterup/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/jquery.counterup.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
    <script src="{% static 'lib/typed/typed.min.js' %}"></script>
    <!-- Contact Form JavaScript fayllari -->
    <script src="{% static 'contactform/contactform.js' %}"></script>

    <!-- Asosiy Javascript fayli -->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

work/templates/addwork.html
<form action="{% url 'work:addwork' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="group">
        <label for="" >IMG</label>
        {{addwork.img}} <br><br>

        <label for="">Name</label>
        {{addwork.name}}<br><br>

        <label for="">TITLE</label>
        {{addwork.title}}<br><br> 
    </div>
    <input type="submit" value="OK">
</form>

work/templates/work.html
{% extends 'index.html' %}
{% load static %}
{% block title %} Portfolio {% endblock %}
{% block content %}
<br><br><br>
<section id="work" class="portfolio-mf sect-pt4 route">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="title-box text-center">
                    <h3 class="title-a">
                        Portfolio
                    </h3>
                    <p class="subtitle-a">
                        Check out my amazing portfolios. Approved by many of my clients.
                    </p>
                    <div class="line-mf"></div>
                </div>
            </div>
            <h3 style="margin:3px auto;"><a class="link" href="{% url 'work:addwork' %}" >ADDWork</a></h3>
        </div>
            <div class="row">
                {% for i in obj %}
                <div class="col-md-4">
                    <div class="work-box">
                        <a href="{{i.img.url}}" data-lightbox="gallery-mf">
                            <div class="work-img">
                                <img src="{{i.img.url}}" alt="" class="img-fluid">
                            </div>
                            <div class="work-content">
                                <div class="row">
                                    <div class="col-sm-8">
                                        <h2 class="w-title">{{i.name}}</h2>
                                        <div class="w-more">
                                            <span class="w-ctegory">{{i.title.upper}}</span> / <span class="w-date">{{i.date}}</span>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="w-like">
                                            <span class="ion-ios-plus-outline"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
            <!-- <!-- <div class="col-md-4">
                <div class="work-box">
                    <a href="{% static 'img/work-2.jpg' %}" data-lightbox="gallery-mf">
                        <div class="work-img">
                            <img src="{% static 'img/work-2.jpg' %}" alt="" class="img-fluid">
                        </div>
                        <div class="work-content">
                            <div class="row">
                                <div class="col-sm-8">
                                    <h2 class="w-title">Akmalov Rustam</h2>
                                    <div class="w-more">
                                        <span class="w-ctegory">Web Design</span> / <span class="w-date">18 Nov.
                                            2020</span>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="w-like">
                                        <span class="ion-ios-plus-outline"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="work-box">
                    <a href="{% static 'img/work-3.jpg' %}" data-lightbox="gallery-mf">
                        <div class="work-img">
                            <img src="{% static 'img/work-3.jpg' %}" alt="" class="img-fluid">
                        </div>
                        <div class="work-content">
                            <div class="row">
                                <div class="col-sm-8">
                                    <h2 class="w-title">Bahriddinov Madrahim</h2>
                                    <div class="w-more">
                                        <span class="w-ctegory">Web Design</span> / <span class="w-date">18 Nov.
                                            2020</span>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="w-like">
                                        <span class="ion-ios-plus-outline"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="work-box">
                    <a href="{% static 'img/work-4.jpg' %}" data-lightbox="gallery-mf">
                        <div class="work-img">
                            <img src="{% static 'img/work-4.jpg' %}" alt="" class="img-fluid">
                        </div>
                        <div class="work-content">
                            <div class="row">
                                <div class="col-sm-8">
                                    <h2 class="w-title">Bobur Boymamatov</h2>
                                    <div class="w-more">
                                        <span class="w-ctegory">Web Design</span> / <span class="w-date">18 Nov.
                                            2020</span>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="w-like">
                                        <span class="ion-ios-plus-outline"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="work-box">
                    <a href="{% static 'img/work-5.jpg' %}" data-lightbox="gallery-mf">
                        <div class="work-img">
                            <img src="{% static 'img/work-5.jpg' %}" alt="" class="img-fluid">
                        </div>
                        <div class="work-content">
                            <div class="row">
                                <div class="col-sm-8">
                                    <h2 class="w-title">Xafizov Aslbek</h2>
                                    <div class="w-more">
                                        <span class="w-ctegory">Web Design</span> / <span class="w-date">18 Nov.
                                            2020</span>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="w-like">
                                        <span class="ion-ios-plus-outline"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="work-box">
                    <a href="{% static 'img/work-6.jpg' %}" data-lightbox="gallery-mf">
                        <div class="work-img">
                            <img src="{% static 'img/work-6.jpg' %}" alt="" class="img-fluid">
                        </div>
                        <div class="work-content">
                            <div class="row">
                                <div class="col-sm-8">
                                    <h2 class="w-title">Ma'mirzayev Suhrob</h2>
                                    <div class="w-more">
                                        <span class="w-ctegory">Web Design</span> / <span class="w-date">18 Nov.
                                            2020</span>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="w-like">
                                        <span class="ion-ios-plus-outline"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>-->

        </div> 
    </div>
</section>

<div class="testimonials paralax-mf bg-image" style="background-image: url({% static 'img/overlay-bg.jpg' %})">
    <div class="overlay-mf"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div id="testimonial-mf" class="owl-carousel owl-theme">
                    <div class="testimonial-box">
                        <div class="author-test">
                            <img src="{% static 'img/testimonial-2.jpg' %}" width="150px" height="150px" alt=""
                                class="rounded-circle b-shadow-a">
                            <span class="author">Allayorov Yusuf</span>
                        </div>
                        <div class="content-test">
                            <p class="description lead">
                                I started a job and I will continue to the end and finish it. I believe in my own
                                experience. I try to project as our clients want.
                            </p>
                            <span class="comit"><i class="fa fa-quote-right"></i></span>
                        </div>
                    </div>
                    <div class="testimonial-box">
                        <div class="author-test">
                            <img src="{% static 'img/testimonial-4.jpg' %}" width="150px" height="150px" alt=""
                                class="rounded-circle b-shadow-a">
                            <span class="author">Xafizov Aslbek</span>
                        </div>
                        <div class="content-test">
                            <p class="description lead">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore nulla facilis
                                itaque cupiditate accusantium deserunt omnis placeat at error molestiae.
                            </p>
                            <span class="comit"><i class="fa fa-quote-right"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}